# 代理地址，及其端口

#不使用代理
#proxy:
#  host: ''
#  port: ''

# 使用代理
proxy:
  host: '127.0.0.1'
  port: '7890'

# cookie字段，'PHPSESSID' 的值
cookie: '108661283_PuGpDkjGM0kASj70DaSPqH9SkOFK0SYE'

# 爬虫开始界面
startPage: 'https://www.pixiv.net/ranking.php?mode=male'

# 文件储存路径，以jar包位置为起始
imgSavePath: '%HERE%/img'

# 文件传输（ssh）
ssh:
  remoteDir: '/remote/directory/'
  userName: 'root'
  remoteHost: 'test.com'
  remotePort: '22'
  password: '123wqeasd'